<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DonorsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('donors')->truncate();
        DB::table('donors')->insert([
            ['full_name' => 'أحمد يوسف','email' => 'ahmed@example.com','country' => 'Italy','amount' => 50.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'John Smith','email' => 'john.smith@example.com','country' => 'USA','amount' => 20.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Maria Rossi','email' => 'maria.rossi@example.com','country' => 'Italy','amount' => 20.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'محمد علي','email' => 'mohamed.ali@example.com','country' => 'Egypt','amount' => 30.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Sarah Johnson','email' => 'sarah.j@example.com','country' => 'UK','amount' => 90.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'يوسف حسن','email' => 'youssef.hassan@example.com','country' => 'Jordan','amount' => 45.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Ali Khan','email' => 'ali.khan@example.com','country' => 'Pakistan','amount' => 60.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Emily Brown','email' => 'emily.brown@example.com','country' => 'Canada','amount' => 50.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'خالد محمود','email' => 'khaled@example.com','country' => 'Palestine','amount' => 25.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Laura Müller','email' => 'laura.m@example.com','country' => 'Germany','amount' => 10.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'ليلى أحمد','email' => 'leila@example.com','country' => 'Sudan','amount' => 40.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Carlos Garcia','email' => 'carlos@example.com','country' => 'Spain','amount' => 95.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'سامي إبراهيم','email' => 'sami@example.com','country' => 'Kuwait','amount' => 70.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Olivia Davis','email' => 'olivia.d@example.com','country' => 'Australia','amount' => 30.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'هند محمد','email' => 'hend@example.com','country' => 'Saudi Arabia','amount' => 55.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'David Lee','email' => 'david.lee@example.com','country' => 'Singapore','amount' => 60.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'مازن خالد','email' => 'mazen@example.com','country' => 'Qatar','amount' => 35.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Sophie Martin','email' => 'sophie@example.com','country' => 'France','amount' => 140.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'علياء سمير','email' => 'alya@example.com','country' => 'UAE','amount' => 65.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'James Wilson','email' => 'james.w@example.com','country' => 'USA','amount' => 15.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'زينب حسين','email' => 'zainab@example.com','country' => 'Iraq','amount' => 50.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Hiroshi Tanaka','email' => 'hiroshi@example.com','country' => 'Japan','amount' => 70.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'منى عبدالله','email' => 'mona@example.com','country' => 'Bahrain','amount' => 60.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Omar Farouk','email' => 'omar.f@example.com','country' => 'Egypt','amount' => 45.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Isabella Conti','email' => 'isabella@example.com','country' => 'Italy','amount' => 20.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'مروان عبد الله','email' => 'marwan@example.com','country' => 'Jordan','amount' => 70.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Sophia Taylor','email' => 'sophia.t@example.com','country' => 'UK','amount' => 15.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'عادل عمر','email' => 'adel@example.com','country' => 'Palestine','amount' => 25.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Lucas Meyer','email' => 'lucas.m@example.com','country' => 'Germany','amount' => 95.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'نسرين محمد','email' => 'nasreen@example.com','country' => 'Morocco','amount' => 80.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Andreas Schmidt','email' => 'andreas.s@example.com','country' => 'Germany','amount' => 25.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'رنا حسين','email' => 'rana@example.com','country' => 'Lebanon','amount' => 55.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Victor Hugo','email' => 'victor@example.com','country' => 'France','amount' => 40.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'ياسين خالد','email' => 'yassin@example.com','country' => 'Algeria','amount' => 35.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Emma Johnson','email' => 'emma.j@example.com','country' => 'USA','amount' => 15.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'هالة إبراهيم','email' => 'hala@example.com','country' => 'Egypt','amount' => 60.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Pedro Alvarez','email' => 'pedro@example.com','country' => 'Spain','amount' => 90.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'حسين مصطفى','email' => 'hussein@example.com','country' => 'Kuwait','amount' => 75.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Anna Nowak','email' => 'anna.n@example.com','country' => 'Poland','amount' => 15.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'ليان يوسف','email' => 'lian@example.com','country' => 'Qatar','amount' => 50.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Ethan Brown','email' => 'ethan.b@example.com','country' => 'Canada','amount' => 30.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'آدم محمود','email' => 'adam@example.com','country' => 'Saudi Arabia','amount' => 40.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Charlotte Green','email' => 'charlotte.g@example.com','country' => 'Australia','amount' => 10.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'يوسف عادل','email' => 'y.adel@example.com','country' => 'Egypt','amount' => 55.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Noah Anderson','email' => 'noah.a@example.com','country' => 'USA','amount' => 80.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'سلمى خالد','email' => 'salma@example.com','country' => 'Palestine','amount' => 25.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Jakob Lund','email' => 'jakob.l@example.com','country' => 'Denmark','amount' => 10.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'مريم عيسى','email' => 'mariam@example.com','country' => 'Jordan','amount' => 65.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
                        ['full_name' => 'William Scott','email' => 'william.s@example.com','country' => 'UK','amount' => 10.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'خديجة عبد الرحمن','email' => 'khadija@example.com','country' => 'Morocco','amount' => 70.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Benjamin Clark','email' => 'ben.clark@example.com','country' => 'USA','amount' => 20.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'طارق حسن','email' => 'tarek@example.com','country' => 'Egypt','amount' => 50.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Hannah White','email' => 'hannah.w@example.com','country' => 'Canada','amount' => 10.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'أيمن خالد','email' => 'ayman@example.com','country' => 'Palestine','amount' => 30.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Mia Lopez','email' => 'mia.l@example.com','country' => 'Mexico','amount' => 10.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'عبدالله ناصر','email' => 'abdullah@example.com','country' => 'Saudi Arabia','amount' => 45.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Oliver Hall','email' => 'oliver.h@example.com','country' => 'UK','amount' => 15.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'منى صادق','email' => 'mona.s@example.com','country' => 'Lebanon','amount' => 65.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Lucas Wagner','email' => 'lucas.w@example.com','country' => 'Germany','amount' => 15.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'أسماء جمال','email' => 'asmaa@example.com','country' => 'Egypt','amount' => 35.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Daniel Kim','email' => 'daniel.k@example.com','country' => 'South Korea','amount' => 15.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'رحاب مصطفى','email' => 'rehab@example.com','country' => 'Jordan','amount' => 55.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Thomas Dupont','email' => 'thomas.d@example.com','country' => 'France','amount' => 10.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'سمير عبد الله','email' => 'samir@example.com','country' => 'Tunisia','amount' => 40.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Sophia Martinez','email' => 's.martinez@example.com','country' => 'USA','amount' => 15.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'إبراهيم ياسر','email' => 'ibrahim@example.com','country' => 'Egypt','amount' => 70.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Amelia Brown','email' => 'amelia.b@example.com','country' => 'UK','amount' => 15.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'ليلى خالد','email' => 'layla@example.com','country' => 'Palestine','amount' => 25.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Noah Walker','email' => 'noah.w@example.com','country' => 'Canada','amount' => 15.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'جميلة حسن','email' => 'jamila@example.com','country' => 'Morocco','amount' => 60.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Jack Miller','email' => 'jack.m@example.com','country' => 'Australia','amount' => 90.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'حازم محمود','email' => 'hazem@example.com','country' => 'Egypt','amount' => 50.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Ella Hughes','email' => 'ella.h@example.com','country' => 'Ireland','amount' => 75.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
                                    ['full_name' => 'محمود صلاح','email' => 'mahmoud@example.com','country' => 'Egypt','amount' => 45.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Grace Carter','email' => 'grace.c@example.com','country' => 'USA','amount' => 60.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'خولة عبد العزيز','email' => 'khawla@example.com','country' => 'Saudi Arabia','amount' => 55.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Liam Harris','email' => 'liam.h@example.com','country' => 'UK','amount' => 180.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'آية مصطفى','email' => 'aya@example.com','country' => 'Palestine','amount' => 30.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Mason Lewis','email' => 'mason.l@example.com','country' => 'Canada','amount' => 70.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'نورهان عادل','email' => 'norhan@example.com','country' => 'Egypt','amount' => 40.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Lucas White','email' => 'lucas.white@example.com','country' => 'Australia','amount' => 90.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'أحلام يوسف','email' => 'ahlam@example.com','country' => 'Morocco','amount' => 65.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Henry Adams','email' => 'henry.a@example.com','country' => 'USA','amount' => 10.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'رامي فؤاد','email' => 'rami@example.com','country' => 'Lebanon','amount' => 55.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Chloe Baker','email' => 'chloe.b@example.com','country' => 'UK','amount' => 85.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'سهى ناصر','email' => 'soha@example.com','country' => 'Jordan','amount' => 35.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Ethan Robinson','email' => 'ethan.r@example.com','country' => 'Canada','amount' => 15.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'منى يحيى','email' => 'mona.y@example.com','country' => 'Egypt','amount' => 50.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Logan Mitchell','email' => 'logan.m@example.com','country' => 'USA','amount' => 75.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'جواد أحمد','email' => 'jawad@example.com','country' => 'Palestine','amount' => 25.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Zoe King','email' => 'zoe.k@example.com','country' => 'Australia','amount' => 15.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'خلود حسن','email' => 'kholoud@example.com','country' => 'Saudi Arabia','amount' => 60.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'هشام عادل','email' => 'hesham@example.com','country' => 'Egypt','amount' => 45.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Ava Thompson','email' => 'ava.t@example.com','country' => 'USA','amount' => 65.00,'campaign' => 'حملة الحليب للأطفال','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'باسم خالد','email' => 'basem@example.com','country' => 'Jordan','amount' => 35.00,'campaign' => 'حملة الخبز','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'Sophia Evans','email' => 'sophia.e@example.com','country' => 'Canada','amount' => 80.00,'campaign' => 'توفير وجبات طعام','created_at' => now(),'updated_at' => now()],
            ['full_name' => 'ريم محمد','email' => 'reem@example.com','country' => 'Egypt','amount' => 50.00,'campaign' => 'توفير حفاضات للأطفال','created_at' => now(),'updated_at' => now()],
        
        ]);
    }
}



